name = "personal-webpage"
main = "dist/_worker.js"
compatibility_date = "2025-09-30"
compatibility_flags = ["nodejs_compat"]

[build]
command = "bun run build"

[assets]
binding = "ASSETS"
directory = "dist"
include = [
  "_astro/**",
  "blog/**",
  "cv/**",
  "favicons/**"
]
exclude = [
  "_worker.js",
  "_routes.json"
]
